[package]
name = "slashook-macros"
description = "Macros for slashook"
categories = ["development-tools"]
version = "0.1.0"
edition = "2018"
authors = ["Tonkku"]
repository = "https://github.com/tonkku107/slashook"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.75", features = ["full"] }
quote = "1.0.9"
proc-macro2 = "1.0.28"
devise = "0.3.1"
